"""Add delivery_person_id to orders

Revision ID: eb8452f12dd8
Revises: 7ae4192241e2
Create Date: 2025-07-26 15:30:40.918254

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb8452f12dd8'
down_revision: Union[str, Sequence[str], None] = '7ae4192241e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('delivery_person_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'orders', 'users', ['delivery_person_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'delivery_person_id')
    # ### end Alembic commands ###
